require 'factory_girl_rails'

namespace :db do
  desc "Fill database with sample data"
  task populate: :environment do

  @users = FactoryGirl.create_list(:user, 4)

  @category1 = Category.create!(name: "Car", active: true, default: true, default: false, outcome: true)
  @category2 = Category.create!(name: "Food & Drink", active: true, default: true, outcome: true)
  @category3 = Category.create!(name: "Family & Personal", active: true, default: true, outcome: true)
  @category4 = Category.create!(name: "Bills", active: true, default: true, outcome: true)
  @category5 = Category.create!(name: "Entertainment", active: true, default: false, outcome: true)
  @category6 = Category.create!(name: "Travel", active: true, default: true, outcome: true)
  @category7 = Category.create!(name: "Hobbies", active: true, default: false, outcome: true)
  @category8 = Category.create!(name: "Home", active: true, default: true, outcome: true)
  @category9 = Category.create!(name: "Healthcare", active: false, default: false, outcome: true)
  @category10 = Category.create!(name: "Debt", active: false, default: false, outcome: true)
  @category11 = Category.create!(name: "Shopping", active: true, default: true, outcome: true)
  @category12 = Category.create!(name: "Education", active: true, default: true, outcome: true)
  @category13 = Category.create!(name: "Transport", active: true, default: false, outcome: true)
  @category14 = Category.create!(name: "Other", active: false, default: false, outcome: true)
  @category15 = Category.create!(name: "Cinema", active: false, default: false, outcome: true)
  @category16 = Category.create!(name: "Gifts", active: false, default: false, outcome: true)
  @category17 = Category.create!(name: "Utilities", active: false, default: false, outcome: true)
  @category18 = Category.create!(name: "Rent", active: false, default: false, outcome: true)
  @category19 = Category.create!(name: "Accomodation", active: false, default: false, outcome: true)
  @category20 = Category.create!(name: "Clothing", active: false, default: false, outcome: true)
  @category21 = Category.create!(name: "Drink", active: false, default: false, outcome: true)
  @category22 = Category.create!(name: "Pets", active: false, default: false, outcome: true)
  @category23 = Category.create!(name: "Love", active: false, default: false, outcome: true)
  @category24 = Category.create!(name: "Kids", active: false, default: false, outcome: true)
  @category25 = Category.create!(name: "Savings", active: false, default: false, outcome: true)
  @category26 = Category.create!(name: "Business", active: true, default: true, outcome: false)
  @category27 = Category.create!(name: "Extra Income", active: true, default: true, outcome: false)
  @category28 = Category.create!(name: "Salary", active: true, default: true, outcome: false)

  @location1 = Location.create!(name: "Andrijevica")
  @location2 = Location.create!(name: "Bar")
  @location3 = Location.create!(name: "Berane")
  @location4 = Location.create!(name: "Bijelo Polje")
  @location5 = Location.create!(name: "Budva")
  @location6 = Location.create!(name: "Cetinje")
  @location7 = Location.create!(name: "Danilovgrad")
  @location8 = Location.create!(name: "Golubovci")
  @location9 = Location.create!(name: "Herceg Novi")
  @location10 = Location.create!(name: "Kotor")
  @location11 = Location.create!(name: "Kolasin")
  @location12 = Location.create!(name: "Mojkovac")
  @location13 = Location.create!(name: "Niksic")
  @location14 = Location.create!(name: "Plav")
  @location15 = Location.create!(name: "Pljevlja")
  @location16 = Location.create!(name: "Pluzine")
  @location17 = Location.create!(name: "Podgorica")
  @location18 = Location.create!(name: "Rozaje")
  @location19 = Location.create!(name: "Tivat")
  @location20 = Location.create!(name: "Tuzi")
  @location21 = Location.create!(name: "Ulcinj")
  @location22 = Location.create!(name: "Zabljak")
  @location23 = Location.create!(name: "Savnik")
  @location24 = Location.create!(name: "Petnjica")
  @location25 = Location.create!(name: "Gusinje")
  @location26 = Location.create!(name: "Abroad")

  @users.each do |user|
  	FactoryGirl.create_list(:expense, 4, user: user, category: @category1, location: @location17, outcome: true)
  	FactoryGirl.create_list(:expense, 3, user: user, category: @category2, location: @location14, outcome: true)
  	FactoryGirl.create_list(:expense, 5, user: user, category: @category3, location: @location12, outcome: true)
    FactoryGirl.create_list(:expense, 4, user: user, category: @category3, location: @location11, outcome: true)
  	FactoryGirl.create_list(:expense, 11, user: user, category: @category4, location: @location2, outcome: true)
    FactoryGirl.create_list(:expense, 18, user: user, category: @category5, location: @location5, outcome: true)
  	FactoryGirl.create_list(:expense, 25, user: user, category: @category6, location: @location10, outcome: true)
  	FactoryGirl.create_list(:expense, 12, user: user, category: @category7, location: @location2, outcome: true)
    FactoryGirl.create_list(:expense, 4, user: user, category: @category8, location: @location3, outcome: true)
  	FactoryGirl.create_list(:expense, 4, user: user, category: @category11, location: @location13, outcome: true)
  	FactoryGirl.create_list(:expense, 15, user: user, category: @category12, location: @location18, outcome: true)
  	FactoryGirl.create_list(:expense, 7, user: user, category: @category13, location: @location15, outcome: true)
    FactoryGirl.create_list(:expense, 3, user: user, category: @category26,  location: @location19, outcome: false)
    FactoryGirl.create_list(:expense, 6, user: user, category: @category27,  location: @location21, outcome: false)
    FactoryGirl.create_list(:expense, 4, user: user, category: @category28,  location: @location9, outcome: false)
    FactoryGirl.create_list(:expense, 27, user: user, category: @category26,  location: @location26, outcome: false)
  end

  @users.each do |user|
    BudgetItem.create!(value: 80, budget_date: '2014-03-01', user: user, category: @category1)
    BudgetItem.create!(value: 75, budget_date: '2014-03-01', user: user, category: @category2)
    BudgetItem.create!(value: 154, budget_date: '2014-03-01', user: user, category: @category3)
    BudgetItem.create!(value: 106, budget_date: '2014-03-01', user: user, category: @category4)
    BudgetItem.create!(value: 65, budget_date: '2014-03-01', user: user, category: @category5)
    BudgetItem.create!(value: 82, budget_date: '2014-03-01', user: user, category: @category6)
    BudgetItem.create!(value: 107, budget_date: '2014-03-01', user: user, category: @category7)
    BudgetItem.create!(value: 120, budget_date: '2014-03-01', user: user, category: @category8)
    BudgetItem.create!(value: 150, budget_date: '2014-03-01', user: user, category: @category11)
    BudgetItem.create!(value: 65, budget_date: '2014-03-01', user: user, category: @category12)
    BudgetItem.create!(value: 96, budget_date: '2014-03-01', user: user, category: @category13)

    BudgetItem.create!(value: 87, budget_date: '2014-04-01', user: user, category: @category1)
    BudgetItem.create!(value: 63, budget_date: '2014-04-01', user: user, category: @category2)
    BudgetItem.create!(value: 96, budget_date: '2014-04-01', user: user, category: @category3)
    BudgetItem.create!(value: 54, budget_date: '2014-04-01', user: user, category: @category4)
    BudgetItem.create!(value: 98, budget_date: '2014-04-01', user: user, category: @category6)
    BudgetItem.create!(value: 78, budget_date: '2014-04-01', user: user, category: @category7)
    BudgetItem.create!(value: 109, budget_date: '2014-04-01', user: user, category: @category8)
    BudgetItem.create!(value: 135, budget_date: '2014-04-01', user: user, category: @category11)
    BudgetItem.create!(value: 154, budget_date: '2014-04-01', user: user, category: @category12)
    BudgetItem.create!(value: 101, budget_date: '2014-04-01', user: user, category: @category13)
  end
 end
end